apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "redwine-week4"
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa # created when deploying the MLOps platform, associating with the secret that contains the username and password of the MLflow's MinIO server
    model:
      modelFormat: 
        name: sklearn
      storageUri: s3://mlflow/4/8f043910fba2452ea8802685a66e3f86/artifacts/model # change to the S3 URI of your model artifact
